### ISSUE TITLE
The new endpoints relating to ETH and BETH are not present in the Staking class

### ISSUE THREAD

**Issue by FaberV1978** [binance/binance-connector-java#102]
The new endpoints relating to ETH and BETH are not present in the Staking class

es.
GET /sapi/v1/eth-staking/eth/quota
GET /sapi/v1/eth-staking/eth/history/rewardsHistory

etc.

**Comment by aisling-2** [comment]
Those endpoints are now available with the latest version: https://github.com/binance/binance-connector-java/releases/tag/3.2.0
