### ISSUE TITLE
why recv PONG

### ISSUE THREAD

**Issue by dbSOD** [binance/binance-connector-java#106]
文档上不是说每三分钟服务端会发一个ping吗，为啥我在客户端既能收到ping还能收到PONG???

**Comment by aisling-2** [comment]
@dbSOD 可以把你的 log 粘贴到这里吗？再加上一个可重现的代码。

**Comment by dbSOD** [comment]
> @dbSOD可以把你的日志粘贴到这里吗？再加上一个可替换的代码。

    @Override
    public void onWebsocketPing(WebSocket conn, Framedata f) {
        log.info("onWebsocketPing, {}", f.getOpcode());

        PongFrame pongFrame = new PongFrame((PingFrame) f);
        conn.sendFrame(pongFrame);
    }

    @Override
    public void onWebsocketPong(WebSocket conn, Framedata f) {
        log.info("onWebsocketPong, {}", f.getOpcode());

        PongFrame pongFrame = new PongFrame();
        pongFrame.setPayload(f.getPayloadData());
        conn.sendFrame(pongFrame);
    }


日志上看，既有PING，又有PONG

**Comment by janjian** [comment]
为什么我用同样的代码回复了还是收到太久没响应pong而断开
