### ISSUE TITLE
URLBuilder is not behaving correctly for list type of parameters

### ISSUE THREAD

**Issue by jeet427** [binance/binance-connector-java#119]
When you need to pass an argument of `List` type, for example in `Wallet` class for `com.koinbasket.common.binance.Wallet#dustTransfer`, the `UrlBuilder` does not work properly. It has only handling for Double type and in else block it considers everything to work with `toString`. In case of list argument it forms bad value for the parameter.

**Comment by alplabin** [comment]
It has been added in the latest version: https://github.com/binance/binance-connector-java/releases/tag/3.4.0
