### ISSUE TITLE
Latest version v3.3.0 is has not been published in maven central

### ISSUE THREAD

**Issue by pasaperez** [binance/binance-connector-java#121]
Release 3.3.0 exists but it is not published in maven central.
* https://github.com/binance/binance-connector-java/releases/tag/3.3.0
* https://mvnrepository.com/artifact/io.github.binance/binance-connector-java

**Comment by alplabin** [comment]
Thanks for sharing this info. The version 3.3.0 is now accessible on maven central: https://central.sonatype.com/artifact/io.github.binance/binance-connector-java/versions
