### ISSUE TITLE
Support for new endpoints that replace the removed on v3.3.0

### ISSUE THREAD

**Issue by pasaperez** [binance/binance-connector-java#122]
In v3.3.0 multiple endpoints have been removed that have become deprecated, but no corresponding support has been added for the new endpoints that replace the old ones.
* https://github.com/binance/binance-connector-java/releases/tag/3.3.0
* https://binance-docs.github.io/apidocs/spot/en/#change-log
  * 2024-01-09

**Comment by octavio12345300** [comment]
https://github.com/binance/binance-connector-java/releases/tag/3.3.0
