### ISSUE TITLE
Fiat orders  has no information in the data field

### ISSUE THREAD

**Issue by jrsantur** [binance/binance-connector-java#14]
Good morning, I am trying to have the deposits and withdrawals that I have made in my account and in the data field it does not show any type of information, and it's okay to say that if I have deposits

Request 
LinkedHashMap<String,Object> parameters = new LinkedHashMap<>();
parameters.put("transactionType", "0");
parameters.put("beginTime","1609477200000");
parameters.put("endTime", ""+new Date().getTime());
String result = spotClient.createFiat().orders(parameters);

Response 
{"code":"000000","message":"success","data":[],"total":0,"success":true}

Please what could be happening?

**Comment by 2pd** [comment]
This library is able to send the request and get response,  so it's not an issue from this library.

Please feel free to open a topic at dev.binance.vision,  or get help with customer support regarding the fiat transaction.
