### ISSUE TITLE
Watch dog - Connection recovery 

### ISSUE THREAD

**Issue by smeana** [binance/binance-connector-java#17]
Hello 

Has the connector any watchdog implementation to reconnect the websocket in case of failure or after the 24h limit?

Regards

**Comment by 2pd** [comment]
it's not implemented in the library, recommend having reconnection on the user side.
However we may consider this in later versions.

thank you.

**Comment by chairz** [comment]
The connector now supports onClosingCallBack (https://github.com/binance/binance-connector-java/blob/master/src/main/java/com/binance/connector/client/WebsocketClient.java). You can make use of that to do a reconnection.

**Comment by Alfrad** [comment]
> The connector now supports onClosingCallBack (https://github.com/binance/binance-connector-java/blob/master/src/main/java/com/binance/connector/client/WebsocketClient.java). You can make use of that to do a reconnection.

How?
