### ISSUE TITLE
cant use wsClient.combineStreams(.....) with   DefaultUrls.TESTNET_WSS_URL

### ISSUE THREAD

**Issue by naserkaka** [binance/binance-connector-java#22]
Hi I cant use client.combineStream with this line using TESTNET_WSS_URL

        wsClient  = new WebsocketClientImpl(DefaultUrls.TESTNET_WSS_URL);

my combineStream works fine when using default value

        wsClient  = new WebsocketClientImpl();

**Comment by naserkaka** [comment]
it worked now for some reason :)

**Comment by 2pd** [comment]
thanks
