### ISSUE TITLE
withdrawHistory not working

### ISSUE THREAD

**Issue by l4p4** [binance/binance-connector-java#23]
LinkedHashMap<String,Object> parameters = new LinkedHashMap<>();

SpotClientImpl client = new SpotClientImpl(API_KEY, SECRET_KEY);
String result = client.createWallet().withdrawHistory(parameters);

result is empty !

**Comment by 2pd** [comment]
If  the parameters are sent to the server as you expected, the library has done its job.

What exactly the parameters in your methods?  can you find withdraw records in UI with those parameters?

**Comment by l4p4** [comment]
> If the parameters are sent to the server as you expected, the library has done its job.
> 
> What exactly the parameters in your methods? can you find withdraw records in UI with those parameters?

If you make a call without any parameters added, it should return the last 90 days, right?!

The call I'm making is exactly like this and there is no return, has there been any change in the API to require some minimum date parameter?

**Comment by 2pd** [comment]
can you find transaction by setting startTime and endTime range?

**Comment by l4p4** [comment]
> can you find transaction by setting startTime and endTime range?

Yes! Binance UI show withdraw history.

You have block code working to perform this action? Can you show an example that working to get last 90 days or any other timeframe?

**Comment by l4p4** [comment]
For fiat history need use Fiat endpoint.
