### ISSUE TITLE
Lowercase symbol in stream

### ISSUE THREAD

**Issue by Hazard4U** [binance/binance-connector-java#24]
Symbol has to be lowercase in websocket, but if not, no error occurs and the stream is opened transparently even if it doesn't work.

Do you think it could be a good idea to add an assertion, log a warn or lower case it in WebsocketClientImpl ? Or it is preferable to let the user deal with it ?

https://github.com/binance/binance-connector-java/blob/b32c38ffe6581967d6819a507121c098be5c08fb/src/main/java/com/binance/connector/client/impl/WebsocketClientImpl.java#L73

**Comment by 2pd** [comment]
thanks, we will improve it in next release.

**Comment by 2pd** [comment]
In the latest release, we force the symbol into lower case, so users will not need to worry about it anymore.
