### ISSUE TITLE
How to get open order status?

### ISSUE THREAD

**Issue by chivmengsong** [binance/binance-connector-java#27]
I was trying to detect if open order status has been filled, but I can't seem to find a function that can do that.

I'm using Java.

**Comment by chairz** [comment]
There are 2 ways you can do it,
1. Restful endpoint (https://github.com/binance/binance-connector-java/blob/master/src/test/java/examples/trade/GetOrder.java). You can query the get order endpoint using the orderID and the server will return the status of this order.

2. Establishing a user data stream via websocket. (https://github.com/binance/binance-connector-java/blob/master/src/test/java/examples/websocket/UserStream.java). You can listen to the ORDER_UPDATE event (https://binance-docs.github.io/apidocs/spot/en/#payload-order-update), this will be pushed to you once there is a change in your order status.

**Comment by chivmengsong** [comment]
Thanks for your fast respond, I'll check it out and update on this topic

**Comment by chivmengsong** [comment]
Hey, I manage to do the query as you said, I tried to do with web-socket, but it"s getting slow when I tried to gather the information. It always return null whenever the client haven't connect successfully.

**Comment by chairz** [comment]
This is a connectivity issue problem on your end. Ensure you have stable connection to the server.

**Comment by chivmengsong** [comment]
Thanks
