### ISSUE TITLE
Wrong timestamp

### ISSUE THREAD

**Issue by l4p4** [binance/binance-connector-java#28]
` public static final String buildTimestamp() {
        return String.valueOf(System.currentTimeMillis());
    }
`

Im get {"code":-1021,"msg":"Timestamp for this request is outside of the recvWindow."}, using postman and pass my params all work fine, but when using lib the currentTimeMillis is wrong

**Comment by 2pd** [comment]
You may need to sync your local time.

**Comment by l4p4** [comment]
> You may need to sync your local time.

How to do? Timezone is set. I increase recvwindow and work but default currentmillis not work, maybe nano better?

**Comment by chairz** [comment]
The default recvWindow is 5000ms. If you have high network latency, it is recommendable that you increase the recvWindow size. The higher the recvWIndow, the higher the tolerance for network latency. The largest recvWindow you can set is 60000ms. You can read more about recvWindow on our API documentation.

**Comment by l4p4** [comment]
> The default recvWindow is 5000ms. If you have high network latency, it is recommendable that you increase the recvWindow size. The higher the recvWIndow, the higher the tolerance for network latency. The largest recvWindow you can set is 60000ms. You can read more about recvWindow on our API documentation.

I think that is about other thing, using postman work fine w default recvwindow. But is work with max recvwindow, so ll close. Thanks guys
