### ISSUE TITLE
universalTransfer Unsupported operation

### ISSUE THREAD

**Issue by lsalenko** [binance/binance-connector-java#33]
Hi, 

I want to make transfer between subaccounts, I'm using `createSubAccount().universalTransfer` method.
Generated request is
`https://api.binance.com/sapi/v1/sub-account/universalTransfer?fromEmail=a&toEmail=b&fromAccountType=SPOT&toAccountType=SPOT&asset=DAI&amount=1&timestamp=1653671807424&signature=6c267d5ef333243dd5d47a3e520384fba43ce20e1858582d64b004456844338e`
and response is 
`{"code":-9000,"msg":"Unsupported operation"}`
(status 400)

My API has 'Enable Internal Transfer' option enabled
Please help )

EDIT: i suspect that my account type is broker account, could it be the reason? And how I can check type of account to be sure?

**Comment by chairz** [comment]
This has nothing to do with the functionality of the connector. Please direct your API questions to the `[dev forum](https://dev.binance.vision/)`
