### ISSUE TITLE
Field asset is not mandatory 

### ISSUE THREAD

**Issue by l4p4** [binance/binance-connector-java#34]
public String flexibleProductPosition(LinkedHashMap<String, Object> parameters) {
        ParameterChecker.checkParameter(parameters, "asset", String.class);
        return this.requestHandler.sendSignedRequest(this.baseUrl, "/sapi/v1/lending/daily/token/position", parameters, HttpMethod.GET, this.showLimitUsage);
    }

When not set, return list with all product positions.

A suggest remove this checkParameter to asset.

**Comment by chairz** [comment]
Thank you for spotting this, will remove the parameter restriction in the next release.

**Comment by chairz** [comment]
Fixed in #35
