### ISSUE TITLE
outdated code examples

### ISSUE THREAD

**Issue by AlberoPazzo** [binance/binance-connector-java#36]
the logger.log(); written in the examples chenged to logger.info();

**Comment by chairz** [comment]
Which example file are you referring to? We use logger.info for all printing in our examples.

**Comment by AlberoPazzo** [comment]
inside the README below [Response MetaData](https://github.com/binance/binance-connector-java#response-metadata) and [Error](https://github.com/binance/binance-connector-java#error)

**Comment by chairz** [comment]
That is true. Thank you for spotting the mistake. This will be changed in the upcoming release.

**Comment by chairz** [comment]
Resolved in #40
