### ISSUE TITLE
logback.xml 有必要提交上来吗?

### ISSUE THREAD

**Issue by bugZhang** [binance/binance-connector-java#4]
如果要实现自己的日志配置岂不是很麻烦

**Comment by jacklealoveyou** [comment]
是的啊，项目日志logback-spring.xml 在logback.xml 之后,怎么剔除这个logback

**Comment by jacklealoveyou** [comment]
怎么去掉这个logback.xml，我项目上是spring-logback.xml 指定了配置文件，还是会生成binance-java-connector.log

**Comment by chairz** [comment]
把logback.xml的设置替换成自己日志的设置就可以了

**Comment by ricksoft** [comment]
The problem happen for spring boot application configuration, you have to use spring-logback.xml instead of logback.xml in order to use Spring Logback Extensions. This issue force devs to include both in order to disable your logging.
