### ISSUE TITLE
Track onFailure for websocket and check if websocket connection is alive

### ISSUE THREAD

**Issue by naserkaka** [binance/binance-connector-java#45]
Hi ,

1.  how can I check if my websocket connection is open/running ? 

3. I wonder if the openEvent,closingEvent and FailureEvent variables can return a value other than null ? I would like to know why my websocket is failing sometimes. 

             onOpenCallbackMarket = openEvent -> {
       
            };
             onMessageCallbackMarket = (message) -> {
                
           };
            onClosingCallbackMarket = closingEvent -> {

            };
            onFailureCallbackMarket = failureEvent -> { 
           
           };

**Comment by chairz** [comment]
https://github.com/binance/binance-connector-java/blob/master/src/test/java/examples/websocket/TradeStreamWithAllCallbacks.java

You can take a look at this example file. It handles callbacks from websocket.

**Comment by naserkaka** [comment]
@chairz  it just restarts the websocket. Is it possible to get a message why it failed ?

**Comment by Hazard4U** [comment]
@naserkaka I have proposed a [PR](https://github.com/binance/binance-connector-java/pull/51) about this idea, without knowing you had asked for. Maybe you can review it and see if it fits your needs.

**Comment by naserkaka** [comment]
Hi @Hazard4U , this will help a lot , now I can catch the error for failureOnCallback  and see more detailed information why it failed. This was needed, thanks!

**Comment by naserkaka** [comment]
so this is how I can catch the message in onFailure ? for now.

     onFailureCallbackMarketDataUser = (message) -> {
                    logger.error("onFailureCallback() message:" + message);
                };

**Comment by aisling-2** [comment]
Hi @naserkaka, happy to say we've merged @Hazard4U 's PR along with some other adjustments to make callbacks pass the original data to the user.
It's available now at newly released `3.0.0rc2 `and an example can be consulted at `src/test/java/examples/websocketstream/TradeStreamWithAllCallbacks.java`. Pls have a try.

This being said, we're closing this issue. Thx.
