### ISSUE TITLE
[“code”:-1102,”msg”:”Mandatory parameter ‘amount’ was not sent”] purchasing staking product with Java API

### ISSUE THREAD

**Issue by kokako80** [binance/binance-connector-java#55]
while using the official Java API Library ( io.github.binance.binance-connector-java v 1.9.0) to execute purchases of Staking products for various assets i came across this error: {“code”:-1102,“msg”:“Mandatory parameter ‘amount’ was not sent, was empty/null, or malformed.”}.
The error occurred only for some assets/products while for other pairs the purchase completed correctly and in every call to the API, the “amount” parameter was correctly set as a Double value as expected by the method “com.binance.connector.client.impl.spot.Staking.purchase(LinkedHashMap<String, Object> parameters)”.

After some troubleshooting I found that the error occurs every time I pass an amount value with decimal digits with every asset/productId pair, while if I pass an integer value, the call completes correctly every time.

Looking at the querystring that is generated with decimal values I found that the library escapes the decimal separator with %2C:

https://api.binance.com/sapi/v1/staking/purchase?product=STAKING&productId=Shib*120&amount=3389%2C34&timestamp=1663486749228&signature=xxxxxxxxxxx

while with integer values there are no escapes and the call succedes:

https://api.binance.com/sapi/v1/staking/purchase?product=STAKING&productId=Shib*120&amount=3389&timestamp=1663487010880&signature=xxxxxxxxxxx

Investigating more on the issue, I found that probably lies in DecimalFormat conversion with locales that differ from EN or US, in fact I'm reproducing the issue on a machine with IT locale.

In class ```com.binance.connector.client.utils.UrlBuilder``` there is a method ```getFormatter()``` to obtain a ```DecimalFormat``` to convert to string Numbers. This method's current implementation uses the System current locale to obtain a DecimalFomat instance and this causes issues when the program is running on Locales that use "," instead of "." for decimal separator.

For reference, I fixed the problem forcing the locale symbols for DecimalFormat initialization to Locale.US:
```
  	private static DecimalFormat getFormatter() {
		if (null == df) {
			DecimalFormatSymbols symbols = new DecimalFormatSymbols(Locale.US);
			df = new DecimalFormat("##.########", symbols);
			df.setMaximumFractionDigits(MAX_DECIMAL_DIGITS);
			df.setGroupingUsed(false);

		}
		return df;
	}
```

**Comment by aisling-2** [comment]
Hi @kokako80, thank you for describing the troubleshooting that you've done step by step.
We'll include the fix in the next version release, related PR is at  https://github.com/binance/binance-connector-java/pull/57.
FYI, we'll option for `#,##0.###` to not drop 0 if a double is for example 0.666.
