### ISSUE TITLE
Why library is not using POJO?

### ISSUE THREAD

**Issue by jimmyheller** [binance/binance-connector-java#60]
Hello everyone!

Since there is no discussion part I'm going to use an issue for it. I noticed that the library uses `String` class to return the responses from the Binance. I am curious to know what is the reason behind it. Why have the POJOs not been used for this purpose? also inputs are dynamic and used `LinkedHashMap` .

**Comment by 2pd** [comment]
We may improve it in later version.  With LinkedHashMap as the input,  users still can possibility use the library if there is change in API endpoint.  As Binance iterating the products so frequently, the result from API endpoints can also changing very quickly.  Without upgrading the library, clients could get all up-to-date json string with the same method.

**Comment by jimmyheller** [comment]
how do you think us as users can contribute to this to improve it?

**Comment by mjcramer** [comment]
Is there a reason for using `LinkedHashMap` as opposed to a simple `Map` interface?

**Comment by 2pd** [comment]
> LinkedHashMap

thanks for the suggestion, we will look into this.

**Comment by 2pd** [comment]
> Is there a reason for using `LinkedHashMap` as opposed to a simple `Map` interface? I'm actually using this library from scala and there are no implicit conversions from scala's `Map` to `LinkedHashMap`, so I have to do something clunky like
> 
> ```
> val parameters = new util.LinkedHashMap[String,Any](parameters.asJava)
> ```
> 
> which, admittedly, isn't THAT big of a deal, but generally API methods use interface classes to allow the user to choose whatever implementation s/he needs.

thanks for the suggestion, we will look into this.

**Comment by aisling-2** [comment]
@mjcramer We've just released a new version 3.0.0rc2 where there's change from `LinkedHashMap` to `Map`.

As for the original message (use of POJO), we haven't had the time to seriously look into it yet, but anyone is free to submit a PR for us to review and accelerate the process (if accepted) :)

**Comment by aisling-2** [comment]
After more research on the possibility of adding POJO classes, we’ve decided to not go forward with this.
Our connector supports a great amount of endpoints and there’s constant changes in their response fields. Maintaining individual POJO classes for each response would require significant effort, and any delays in updating the library could result in old versions of responses being returned, which poses a more serious problem.
