### ISSUE TITLE
Implement Convert Endpoints

### ISSUE THREAD

**Issue by eum2o** [binance/binance-connector-java#63]
The type `com.binance.connector.client.impl.spot.Convert` currently implements the `/sapi/v1/convert/tradeFlow` endpoint. 

According to https://binance-docs.github.io/apidocs/spot/en/#convert-endpoints at least `POST /sapi/v1/convert/getQuote` and `POST /sapi/v1/convert/acceptQuote` seem to be required to actually convert assets. 

It'd be nice to have these endpoints supported by this API.

**Comment by aisling-2** [comment]
Thank you, we look to add those endpoints in future versions as they're still relatively new endpoints.
