### ISSUE TITLE
Remove logback.xml from archive

### ISSUE THREAD

**Issue by jnemecz** [binance/binance-connector-java#64]
Please, remove your `logback.xml` configuration file from final library:

[https://mkyong.com/maven/maven-exclude-logback-xml-in-jar-file/](https://mkyong.com/maven/maven-exclude-logback-xml-in-jar-file/)

It makes confusion in our applications.

**Comment by ricksoft** [comment]
+1

**Comment by ivanhdzd** [comment]
+1

**Comment by aisling-2** [comment]
We've released a new version [2.0.0rc2 ](https://github.com/binance/binance-connector-java/releases/tag/2.0.0rc2), where `logback.xml` has been removed to not interfere the user-end.
