### ISSUE TITLE
keep Alive userDataStream listen key

### ISSUE THREAD

**Issue by naserkaka** [binance/binance-connector-java#67]
Hi ,how can I keepAlive userdata stream listen key ?
Is there any built in function for this ? 

https://binance-docs.github.io/apidocs/spot/en/#user-data-streams

**Comment by aisling-2** [comment]
@naserkaka there's a `extendListenKey()` to keep your listen key alive at https://github.com/binance/binance-connector-java/blob/master/src/main/java/com/binance/connector/client/impl/spot/UserData.java#L57

**Comment by aisling-2** [comment]
Since there's no new updates, we're closing this topic. Feel free to reopen, if there's more questions int he future.
