### ISSUE TITLE
No trading fees from api on testnet

### ISSUE THREAD

**Issue by aymens** [binance/binance-connector-java#7]
I'm using the trading fees from wallet API in my program.

At some time I'll need to test my program on testnet before going on prod with real money.

But, as the trade fees wallet endpoint returns an empty response on testnet (realized that with postman), my program won't run correctly.

Is there a solution to this problem, other than mocking the call to fees endpoint myself?

Thanks

**Comment by chairz** [comment]
Answered on dev.binance.vision

**Comment by aymens** [comment]
Yes indeed. Thanks.
