### ISSUE TITLE
Proxy support for WebsocketClient

### ISSUE THREAD

**Issue by nwang0** [binance/binance-connector-java#72]
The newly added support of proxy in the SpotClient was a godsend. 
Is there any plan to support proxy in the WebsocketClient as well?

**Comment by aisling-2** [comment]
Hi @nwang0, glad you're receiving well the new feature!

Regarding the question, `okhttp` library has limitations when concerning proxy implementation at WebSocket level, so unfortunately we don't have plans to implement it in the short term.
