### ISSUE TITLE
No symbol field specify in 'Partial Book Depth Streams' response?

### ISSUE THREAD

**Issue by SudoHuang** [binance/binance-connector-java#83]
Hi, team.
For 'Partial Book Depth Streams', there is no symbol field in the response payload. 
How does customers recognize the response data in case of multi subscriptions in one connection?

**Comment by aisling-2** [comment]
Hello, for you to get the symbol indication in the response, you can use the ws's `/stream?streams=` approach (https://binance-docs.github.io/apidocs/spot/en/#websocket-market-streams).

At this connector, it is implemented via the `combineStreams()` method, which has an example usage at:
https://github.com/binance/binance-connector-java/blob/master/src/test/java/examples/websocketstream/CombineStreams.java
