### ISSUE TITLE
"timestamp" differs with server time

### ISSUE THREAD

**Issue by DayLightUA** [binance/binance-connector-java#87]
I'm faced with next problem:
My OS has autoSync date/time.
Binance test net server were delayed near 18s. It cause error by Binance Timing security
In current implementation "timestamp" setting is hardcoded:
`parameters.put("timestamp", UrlBuilder.buildTimestamp());` in RequestHandler.class.
` UrlBuilder.buildTimestamp()` uses undercover `System.currentTimeMillis()`.
 
 As result, it is not possible to adjust "timestamp"
 Java not allows to modify systemTime. `UrlBuilder.buildTimestamp()` is static.
 RequestHandler can be extended with methods override, but all Endpoints (Market, Trade, etc) have finalized field requestHandler with initialization in constructor `this.requestHandler = new RequestHandler(apiKey, proxy);`.
 And "timestamp" set hard `Map.put`.
 
 So there haven't any valid way to adjust application time to synchronize with server.
 
 Proposed solutions:
 Simplest solution is to replace  `Map.put` with  `Map.putIfAbsent`, but not the best.
 Best solution from my side is to replace `System.currentTimeMillis()` with usage static variable Clock clock instantiated by default with `Clock systemUTC()`, that can be replaced with OffsetClock object.
 Also, it can be allowed to inject extend of RequestHandler to all endpoints
 
 Thanks!

**Comment by aisling-2** [comment]
Hi @DayLightUA, there's a `recvWindow` parameter you can use to set the time the request is valid for, this parameter is specially used for situations like you've describe, please have a try.
For more details on this you can consult: https://binance-docs.github.io/apidocs/spot/en/#endpoint-security-type

**Comment by DayLightUA** [comment]
Hi @aisling-2 ,
Yes, I know about `recvWindow`. But this parameter applicable only if app sysTime is less than serverTime +1s: `(timestamp < (serverTime + 1000) && (serverTime - timestamp) <= recvWindow)` (https://binance-docs.github.io/apidocs/spot/en/#signed-trade-user_data-and-margin-endpoint-security).

In my case, my sysTime was grater on 18s. Also, I understand that it mostly the problem of testnet server, and main Binance api server should have correct time.

Please, just replace.
`parameters.put("timestamp", UrlBuilder.buildTimestamp());` -> `parameters.putIfAbsent("timestamp", UrlBuilder.buildTimestamp());`
This fix should not affects any, but allows for anyone to setup custom "timestamp".

**Comment by aisling-2** [comment]
Hi @DayLightUA, we've upgraded to `putIfAbsent` in the latest new version (v3.1.0). Thank you.
