### ISSUE TITLE
java.lang.NoSuchMethodError: okhttp3

### ISSUE THREAD

**Issue by magistryo** [binance/binance-connector-java#9]
Hi everyone, Need help - what to do with - java.lang.NoSuchMethodError: okhttp3 ?

Simgle method - 

public String orderCreate(String currency, double price){
    parameters.clear();
    parameters.put("symbol",currency);
    parameters.put("side", "BUY");
    parameters.put("type", "LIMIT");
    //parameters.put("timeInForce", "GTC");
    //parameters.put("quantity", 0.01);
    parameters.put("price", new BigDecimal(price));

    String result = client.createTrade().testNewOrder(parameters);
    //String result = client.createTrade().newOrder(parameters);
    System.out.println(result);
    return result;
}

Create exception

2022-01-27 01:55:24.065[1643237724065] | INFO  | AWT-EventQueue-0 | c.b.c.client.utils.RequestHandler    - POST https://api.binance.com/api/v3/order/test?symbol=ETHUSDT&side=BUY&type=LIMIT&price=10&timestamp=1643237724048&signature=c6195ee4542f50832c5ae35ccf2c8edc03b476c6e60c38fa59515d1328672b29
Exception in thread "AWT-EventQueue-0" java.lang.NoSuchMethodError: okhttp3.RequestBody.create(Ljava/lang/String;Lokhttp3/MediaType;)Lokhttp3/RequestBody;
  at com.binance.connector.client.utils.RequestBuilder.buildApiKeyRequest(RequestBuilder.java:57)
  at com.binance.connector.client.utils.RequestHandler.sendApiRequest(RequestHandler.java:48)
  at com.binance.connector.client.utils.RequestHandler.sendSignedRequest(RequestHandler.java:77)
  at com.binance.connector.client.impl.spot.Trade.testNewOrder(Trade.java:58)

google says need to update okhttp3 library.
But on that version ?
Or how to fix it ?

**Comment by chairz** [comment]
The version is listed in pom.xml, you should be on version 4.9.2

**Comment by magistryo** [comment]
> 

version is 4.9.2 - but still this error.
java version - 8

**Comment by magistryo** [comment]
GET methods works - ok
i think this error only on POST methods - like newOrder and testNewOrder

**Comment by chairz** [comment]
I have created a new project and tested it by using the library from maven and it works fine. Can you check under your project's external libraries and see if you are really using okhttp3 4.9.3 in the project?
![Screenshot 2022-01-28 at 10 58 49 AM](https://user-images.githubusercontent.com/31032561/151479664-37eb8a94-d15f-450e-8f9c-8966334c4f98.png)

**Comment by magistryo** [comment]
> I have created a new project and tested it by using the library from maven and it works fine. Can you check under your project's external libraries and see if you are really using okhttp3 4.9.3 in the project? ![Screenshot 2022-01-28 at 10 58 49 AM](https://user-images.githubusercontent.com/31032561/151479664-37eb8a94-d15f-450e-8f9c-8966334c4f98.png)

Hi, now i manually add this dependency in main project pom.xml - and program crash(now even GET method not work) - see scrensots
![new_err2](https://user-images.githubusercontent.com/26606735/151487746-ad5cc695-4f39-42aa-99b4-739b83592b30.jpg)
![newerr](https://user-images.githubusercontent.com/26606735/151487749-22dc93ad-b5d4-46e4-8b50-c8f377c487b4.jpg)

before that in main project pom.xml - no okhttp3 library, it was only in binance-connector-java pom.xml file

**Comment by chairz** [comment]
Can you run any examples in this repo?

**Comment by magistryo** [comment]
> Can you run any examples in this repo?

Hi i import all repo and run example from it - seems all works (testNewOrder - POST and tickerSymbol - GET)
![Снимок экрана от 2022-01-28 22-28-45](https://user-images.githubusercontent.com/26606735/151609601-dc235e3e-1224-4e8f-b839-3d0d61e12dca.png)

but intellij idea for some reason marks ResponseHandler - as file with error. But examples running - ok
![Снимок экрана от 2022-01-28 22-28-53](https://user-images.githubusercontent.com/26606735/151610036-ce349d8b-748d-40e5-827d-22d395374178.png)

I cant understand why my project not run with same code as in examples - any suggestions ?
Maybe some conflict with another libraries ?

**Comment by magistryo** [comment]
> Can you run any examples in this repo?

Hi chairz - please can you create intellij idea project - with gui form which run
 String result = client.createMarket().tickerSymbol(parameters); and  
 String result = client.createTrade().testNewOrder(parameters);
 and upload it somethere ?
 
 still i have some problems with running api on working project(in examples running ok - but there not running gui form(idea cant see form class in examples folder)), and from working project with gui - still not foun okhhtp3 classes.
 Thanks

**Comment by chairz** [comment]
Did you add the connector as a dependency in pom.xml for your project?

**Comment by ezalves25** [comment]
I imported as dependency, how to do in this case?

**Comment by chairz** [comment]
Can you open a new issue and paste the error details in it?

**Comment by chairz** [comment]
closed due to inactivity
