### ISSUE TITLE
Market constructors

### ISSUE THREAD

**Issue by xcocco** [binance/binance-connector-java#93]
Since market data endpoints have NONE security type, I think it would be a good option to have a constructor with only baseUrl and showLimitUsage parameters without needing to set apiKey and proxy to null in the constructor call

**Comment by aisling-2** [comment]
Hi @xcocco , what you're asking for already exists, please refer to https://github.com/binance/binance-connector-java/blob/master/src/main/java/com/binance/connector/client/impl/SpotClientImpl.java#L45.
By default, the proxy is set to null.
