### ISSUE TITLE
Support all endpoints

### ISSUE THREAD

**Issue by marco-eckstein** [binance/binance-connector-java#96]
Either many endpoints are not supported, or it is quite unclear how they can be called with this library. E.g., there seem to be no _Simple Earn_ endpoints. (`sapi/v1/simple-earn/locked/history/rewardsRecord` etc.) Please add them.

**Comment by aisling-2** [comment]
Hi @marco-eckstein, this is a maintained project, so we do plan to add missing endpoints over the time, however due to other ongoing tasks at the moment, we're not able to add them immediately now.

**Comment by aisling-2** [comment]
We've just released a new version https://github.com/binance/binance-connector-java/releases/tag/3.2.0 containing the latest endpoints.
