### ISSUE TITLE
There is no POST /sapi/v1/margin/max-leverage

### ISSUE THREAD

**Issue by SpotBR** [binance/binance-connector-java#97]
There is no POST /sapi/v1/margin/max-leverage

**Comment by aisling-2** [comment]
Hi @SpotBR, we'll add in the future, thanks for referring here.

**Comment by aisling-2** [comment]
This endpoint is now available with the latest version: https://github.com/binance/binance-connector-java/releases/tag/3.2.0

**Comment by SpotBR** [comment]
Thx! You cute
