### ISSUE TITLE
library return type(s)

### ISSUE THREAD

**Issue by ramarro123** [binance/binance-connector-java#98]
hi,

it's intended that the library return string or object without parsing the actual response into jav models?

it seems more like a wrapper around an http client rather than a library, even params need to be send as map, not like method signature or proper modelized in a java fashion

am i missing something?

**Comment by aisling-2** [comment]
Hello, I believe the final response in https://github.com/binance/binance-connector-java/issues/60 is related to your question.    While we understand what you expressed, unfortunately giving the current bandwidth, this is not something we can do.
